/*	$Id: communities-masthead.js,v 1.23 2008/12/11 09:28:57 mbaierl Exp $ */
var akamai_prefixes = {akamai_prefix_developerworks: '//dw1.s81c.com/developerworks/i/dw-lc/', akamai_prefix_ibm: '//dw1.s81c.com/'};(function(){if(typeof window.helpLang==="undefined"){window.helpLang=""}if(typeof window.openHelpWindow==="undefined"){window.openHelpWindow=function(){}}var A={cssJSURL:"//dw1.s81c.com/developerworks/css/dw-lc/",imgURL:"//dw1.s81c.com/developerworks/i/",i18nURL:"//dw1.s81c.com/common/js/dynamicnav/",init:function(){var E=null;jQuery("#communities-logo a:eq(0)").hover(function(){if(E!==null){clearTimeout(E);E=null}A.openMastheadMenu(this);
return false},function(){E=setTimeout(A.closeMastheadMenu,1000)});jQuery("#communities-menu").hover(function(){if(E!==null){clearTimeout(E);E=null}return false},function(){E=setTimeout(A.closeMastheadMenu,1000);return false});jQuery("#communities-nav a").hover(function(){jQuery(this).addClass("hover");A.closeMastheadMenu()},function(){jQuery(this).removeClass("hover")});if(typeof window.appName!=="undefined"){var C="lotusBanner"+window.appName.charAt(0).toUpperCase()+window.appName.substring(1),D=document.getElementById(C);
if(D!==null){D.getElementsByTagName("a").item(0).className+=" active"}}var B=jQuery("#headerUserName");if(B.children().length>0){B.hide()}if(jQuery("#loginForm").length>0){jQuery("#ibm-footer-module ul, #communities-nav, #communities-login").hide();jQuery("#j_username")[0].focus()}},openMastheadMenu:function(){var B=arguments[0]||jQuery("#communities-logo a:eq(0)");if(!B.jquery){B=jQuery(B)}B.find("img:eq(0)").attr("src",A.imgURL+"dw-lc-ibm-logo-open.gif").end().removeClass("menu-closed").addClass("menu-open");
jQuery("#communities-menu").removeClass("menu-closed").addClass("menu-open").css("left",B.offset().left)},closeMastheadMenu:function(){var B=arguments[0]||jQuery("#communities-logo a:eq(0)");if(!B.jquery){B=jQuery(B)}B.find("img:eq(0)").attr("src",A.imgURL+"dw-lc-ibm-logo-close.gif").end().removeClass("menu-open").addClass("menu-closed");jQuery("#communities-menu").removeClass("menu-open").addClass("menu-closed")},preInit:function(){var D=document.createElement("link");D.setAttribute("type","text/css");
D.setAttribute("rel","stylesheet");D.setAttribute("href",A.cssJSURL+"dwcommon-2009-09.css");A.preload(A.imgURL+"mast_ibm_logo_menu_open.gif",A.imgURL+"dw-lc-mast-menu-foot.png",A.imgURL+"dw-lc-mast-menu.png");var B=(typeof (dojoLocale)!="undefined")?dojoLocale:navigator.userLanguage;if(!B){B=navigator.language}if(!B&&typeof (dojo)!="undefined"){B=dojo.locale}if(!!B&&B!=""&&B.length==5){B=B.toLowerCase();var F=B.substr(3,2);var E=B.substr(0,2);
var C=A.i18nURL+F+"/"+E+"/"+F+E+"-utf8.js";jQuery.ajax({url:C,dataType:"script",cache:true,success:A.updateMenu})}},preload:function(){var B;for(var C=0;C<arguments.length;C++){B=new Image();B.src=arguments[C]}},updateMenu:function(){if(typeof (PMM)=="undefined"||typeof (PMM.menuData)=="undefined"){return }var C=jQuery("#communities-menu ul");C.find("li").remove();for(var D=0,B=PMM.menuData.length;D<B;D++){var E=PMM.menuData[D];var F=jQuery("<a></a>").attr("href",E.url).text(E.title).wrap("<li></li>").parent();
if(D==0){F.addClass("lotusFirst");F.find("a").text("ibm.com "+E.title)}F.appendTo(C)}}};A.preInit();jQuery(A.init);jQuery(function(){var C=jQuery("#AddWeblogEntryCommentLink");if(C.length==0){return }var B=jQuery("<a></a>").text(C.text());if(C.hasClass("disabledLink")){B.addClass("disabledLink")}else{B.addClass("lotusAction").attr("href","#").click(function(){C.click();return false})}/*jQuery("div.lotusMeta").append("&nbsp;&nbsp;|&nbsp;&nbsp;").append(B)*/});if(location.href.indexOf("/activities/")!=-1){ibmCommon.queue.push(function(){return jQuery("#activityButtons button").length!=0
},function(){jQuery("#activityButtons button").click(function(){ibmCommon.queue.push(function(){return jQuery("span.buttonIcon.fileIcon").length!=0},function(){jQuery("span.buttonIcon.fileIcon").parent().hide()})})})}})();
