var semtagrs = {'label.semtag.hover.alt': 'Click to view business card for ',
'label.semtag.hover': 'Click here to view business card',
'label.semtag.hover.disabled': 'This profile has been disabled.',
'temp': 'temp'};var lc_default = {'label.overview': 'Overview',
'errors.suffix': '<br />',
'error.title.mail.notauthenticated': 'Your login has timed out.  Please log in using the main Groups window.',
'label.photo.help': 'Optional: You can upload an image that will appear in the overview page for this group. Please ensure that only a business-appropriate photo is placed on this site. The photo must be in JPEG, GIF, or PNG format. Larger images may take several minutes to upload.',
'deleteWidget': 'Remove Widget',
'popup.allcomms.tags': 'Group tags are keywords that indicate the subject or focus of the group. Click a tag to see groups tagged with that keyword.',
'label.top.buttons.edit': 'Edit Group',
'label.form.tips.policy': 'The level of access for a group can be set to open (anyone can see and join), moderated (anyone can see, but you must ask to join), or restricted (only visible to members). You can amend the access level of a group at any time using the Edit Group form.',
'label.previous': 'Previous page',
'label.forum.discussion.edit': 'Edit',
'label.communities': 'Groups',
'label.theme.name.goldencoffee': 'Golden Coffee',
'label.alt.public': 'This is a public group',
'label.public.community.alt.text': 'This is a public group',
'invite.label.max.char': 'Maximum 3000 characters',
'label.meta.dcLanguage': 'en',
'search_searchResults': 'Search Results',
'label.banner.help': 'Help',
'label.welcome.start': 'Get started',
'toggle': 'Toggle',
'widgetCat_AllWidgets': 'All Widgets',
'CUSTOM_WIDGET_TITLE_EXCEED_MAX': 'The title must not exceed 75 characters.',
'communities.metric.publicinvite.communities': 'Total number of public invite only groups',
'label.forum.forumtopics': 'Forum Topics',
'label.all': 'All',
'search.label.input.prompt': 'Enter keyword',
'label.action.confirm.create.community': 'You&apos;ve just created a group: {0}',
'label.include.app': 'Include this application in the group: {0}',
'error.title.userXXXNotFound': 'The user cannot be found: {0}',
'tools.options2': 'From Firefox, click "<b>Tools -> Options</b>".',
'tools.options1': 'Follow these steps to avoid having your bookmark form window display behind your browser window.',
'email.body.jlink.public': '/developerworks/mydeveloperworks/groups/service/html/memberjoinsubmit?returnto=comunityview&communityUuid=',
'label.feed.wait': 'Please wait while the feed is loading...',
'tools.options5': 'Check "<b>Raise or lower windows</b>".',
'tools.options4': 'Click "<b>Advanced</b>".',
'tools.options3': 'Open the "<b>Contents</b>" page.',
'EDIT_INFO': 'The related content widgets will display all content tagged with the keywords you selected below. To modify the tags in the list:<br/><ul><li>Click Group Actions</li><li>Click Edit group</li><li>Enter tags in the field provided</li><li>Save and return to this widget to refine your tag selections</li></ul>',
'label.tagcloud.title.all': 'Tags for Public Groups',
'link.logout': 'Log Out',
'label.side.left.join': 'Join this group',
'label.theme.changelayout': 'Change Layout',
'label.next': 'Next page',
'label.login.user': 'User name:',
'label.url': 'URL:',
'tools.safari.users.instructions': 'Drag the image below to your bookmarks bar.',
'errors.cancel': 'Operation canceled.',
'//added': 'by giovani',
'link.login': 'Log In',
'error.message.invalidCharInOwners': 'The owners list you entered contains invalid characters such as \'?\' and \'*\'.  Please remove these characters from the owner list.',
'label.about.communities': 'About Groups',
'label.welcome.warning': 'Access to the forum is delayed. Please check back in a few minutes.',
'feedreader.nofeed': 'No feed URL has been provided.',
'feedReader': 'Feed Reader',
'error.title.wrongemailinvitation': 'We\'ve encountered a problem.',
'mydw.title': 'developerWorks: Groups',
'Blog': 'Blog',
'label.dispcom.noaccess': '[This group does not allow public access]',
'label.photo.upload': 'Upload an image:',
'label.side.left.confirm': 'Leaving this group will remove you from the membership. ',
'label.theme.name.classicred': 'Classic Red',
'label.outdent': 'Outdent',
'error.title.missing.link': 'Missing link.',
'label.time.format': 'like "1:10 pm" or "11:38 am"',
'popup.recent.feeds': 'These are the most recent feeds added to the group. Any group member can add a feed to the group.',
'communities.metric.login7days.users': 'Number of users logged in the last week',
'mydw.breadcrumb.first': 'developerWorks',
'tips.members': 'These members have joined this group. Hover over a member name to view contact information.',
'label.top.buttons.requestToJoin': 'Request to Join this Group',
'label.text.color': 'Text Color',
'error.recipient.list.too.long': 'The recipient list is too long for the browser to pass to your e-mail client.',
'invite.label.subject': 'Subject:',
'error.title.managed.app.doesnotexist': 'The managed application which this resource or action is associated with does not exist.',
'tooltip.bookmarks': 'Click here to see the group&#146;s bookmarks',
'widgets_Max': 'Maximize',
'label.slider.more': 'more',
'label.date.format': 'like "5/6/1983" or "10/31/08"',
'feedreader.feeds.membercreate': 'Add a feed     ',
'email.body.visittext': 'Visit the group at',
'tools.extensions.label': 'Extension for Internet Explorer and Firefox Web browsers',
'BACK': 'Back',
'label.tagthis': 'Tag content',
'open': 'Open',
'message.findmembers.showingxofx': '** {0} results available. Displaying the first {1} only.',
'errorDefaultMsg2': 'An error has occurred, contact your system Administrator',
'errorDefaultMsg3': 'Click here to show more details',
'errors.double': '{0} must be an double.',
'hideWidgetMsg': 'You are about to hide your widget.<br/><br/>You can re-activate it at a later point simply by re-adding the widget to your Group. All of the Widget content will be kept intact.',
'label.forum.topics.deletedby': 'Deleted by:',
'label.side.left.recent': 'Recent',
'label.form.tips.assappssml': 'You can choose to associate applications with a group, such as wikis, if they are available for your deployment. When you do this, a link and a feed to the parent wiki page are provided in the group\'s overview page.',
'label.managed.apps': 'Managed Applications',
'label.tags.cloud': 'cloud',
'label.mycomm.welcome': 'This is the place where you can keep track of all groups that you have joined.',
'label.icon.private': 'restricted',
'label.top.search': 'Search',
'message.findmembers.noresults': 'No results found for: {0}',
'label.photo.error.type': 'The type of image file you provided is not supported.',
'label.member.alt.delete': 'Click to remove this member from the group',
'label.welcome.alt': 'Close welcome box',
'label.tags.find': 'Find Tags',
'label.morestatistics': 'Server statistics',
'message.findmembers.invalidchars': 'The string you entered contains an invalid character: "{0}".  Please remove it.',
'label.forum.topics.add': 'Post Topic',
'error.title.reference.doesnotexist': 'The feed or bookmark which this resource or action is associated with does not exist.',
'label.communities.all.tag': 'All {0} groups',
'label.link': 'Link:',
'atom.app.community.forum.title': '{0} Discussion Forum',
'label.tagcloud.title.related': 'Related Tags',
'label.theme.name.custom': 'Custom Theme',
'label.form.discussion.delete': 'Delete Entry',
'link.photo.upload': 'Upload an image for your group',
'EDIT_HEADING': 'Choose up to five tags to identify related content',
'label.completedfor': 'Completed for {0} ',
'label.about.colone1': 'Find a group that works for you',
'label.about.colone2': 'Browse or search for groups of interest to you. Click a tag in the tag cloud to find groups tagged with a specific keyword. You can also browse by categories such as Recent (recently updated), Popular, and Alphabetical. When you join a group, you can view bookmarked information, connect with other members, and subscribe to feeds to keep informed.',
'label.about.colone3': 'Give your group the tools it needs',
'label.about.colone4': 'As a group owner, you can make different types of functionality available to members by adding widgets from the content palette. The choice of widgets that you can add to a group depends on what your administrator has made available. Click Customize to open the content palette and see what you can add to your group.',
'error.failedToAdd.multiple.members': 'You have failed to add {0} members to this group.',
'confirm.modified.multiple.members': 'You have successfully updated {0} members in this group.',
'label.meta.metacountry': 'ZZ',
'errors.integer': '{0} must be an integer.',
'feedreader.feeds.membercreatefirst': 'Add your first feed',
'label.dispcom.updated': 'Updated by',
'label.of': '{0}-{1} of {2}',
'communities.metric.login7days.users.desc': 'Total number of distinct logged in users in the last 7 days',
'atom.error.forbidden': 'You are not authorized to perform the requested action.',
'label.forum': 'Forum',
'widgets_MoveDown': 'Move Down',
'label.action.confirm.community.join': 'Welcome to the group, thank you for joining',
'cancel': 'Cancel',
'errorMsg': 'Message: ',
'communities.metric.totals.communities.desc': 'Number of all groups (public, public invite, and restricted).',
'label.form.tips.image': 'When you create a group, you can associate a specific image with the group. The image you choose should be closely associated with the group\'s identity. You can change the image at a later stage using the Edit Group form.',
'label.owners': 'Owners:',
'actions': 'Actions',
'label.photo.error.size': 'The image file you provided is too large.',
'label.tags.tags': 'Tags',
'label.metrics.name': 'Name',
'label.owner': 'owner',
'label.theme.name.custom4': 'Custom Theme 4',
'label.theme.name.custom3': 'Custom Theme 3',
'label.theme.name.custom2': 'Custom Theme 2',
'label.theme.name.custom1': 'Custom Theme 1',
'error.message.generic': 'Something went wrong - click the Back button and try again. If this does not work, report the problem in the support forum.',
'tools.add.bookmarklet.bookmark.title': 'Add to group',
'errors.label.show.full.error': 'Show full error message',
'label.tags.view': 'View as ',
'error.message.server.failed.initialization': 'The server failed to initialize the Groups application.  Contact your system administrator or try again later.',
'confirm.added.members': 'You have successfully added the following people to this group: {0}.',
'errors.email': '{0} is not a valid e-mail address.',
'label.name': 'Name:',
'button.save': 'Save',
'CUSTOM_WIDGET_NO_TITLE_ERROR': 'You must add a title to the widget.',
'label.slider.less': 'less',
'INFO_NOTAG': '<p>There is no related content available matching the selected keywords.</p>',
'label.footer.rest': 'REST API',
'label.public.community.type.text': 'Public',
'label.footer.json.help': 'JSON Help',
'label.top.buttons.inviteToJoin': 'Invite Others to Join',
'link.remove': 'Remove',
'error.failedToAdd.members': 'You have failed to add the following people to this group: {0}.',
'error.required.fields.empty': 'You have left some required fields blank. Please fill in required fields, indicated by the * character in the form.',
'tools.alt.dragthis': 'Drag this button',
'label.footer.moreplugins': 'More Plug-ins',
'feedreader.tags': 'Tags:  ',
'label.meta.metaAbstract': 'On developerWorks Groups, IBMs resource for developers and IT professionals, access tools, code, training, forums, blogs, community, standards, IT samples, downloads and how-to documentation for Rational, WebSphere, Information Management, Lotus, Tivoli, AIX and UNIX, architecture, and Web development, plus open source development and cross-platform, open standards technologies including Java, Linux, XML, SOA and Web services, Autonomic computing, Multicore acceleration.',
'label.build': 'Build {0}',
'label.for.person': 'Groups for <a href="{0}">{1}</a>',
'label.last.bookmarks': 'Last {0} Bookmarks',
'confirm.modified.member': 'You have successfully updated {0} in this group.',
'info.virus.scanning.on': 'Virus scanning enabled, using server(s) {0}',
'communities.metric.login24hr.users.desc': 'Total number of distinct logged in users in the last 24 hours',
'label.icon.public': 'public',
'errors.open.activities': 'Groups Error',
'error.multipleedits': 'Multiple edit forms are not allowed.',
'tips.tags.title': 'Tags:',
'search_communitycontentTag': 'Group content with tags: {0}',
'label.form.feed.add': 'Add Feed',
'atom.error.communityNotFound': 'The referenced group does not exist.',
'label.ibm': 'IBM (r)',
'confirm.removed.member': 'You have successfully removed {0} from this group.',
'//email.body.end.jgroup': 'wants you to join this group:',
'popup.feeds.tags': 'Tags are keywords that are used to categorize the feeds in a group. Click a tag to see the feeds that are tagged with that keyword.',
'login.copyright': 'Licensed Materials - Property of IBM Corp. © IBM Corporation 2007, 2009. IBM, the IBM logo, ibm.com and Lotus are trademarks of IBM Corporation in the United States, other countries, or both. U.S. Government Users Restricted Rights: Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp. Please see the About page for further information. ',
'label.welcome.info2.old': 'You have just created a new group. Use your group to share information and raise awareness about your topic.',
'label.stats.value': 'Value',
'label.tags.delimiter': ',',
'label.theme.name.custom5': 'Custom Theme 5',
'error.message.duplicate.community': 'The name of the group you are trying to create is already taken, please select a different name. Hit the browser Back button to go back and try again.   ',
'label.forum.discussion.wait': 'Please wait while the discussion is loading...',
'label.subscribe.feed.feeds': 'Feed for Group Feed List',
'atom.app.community.overview.title': '{0} Group Feed',
'label.form.tips.assapps': 'You can choose to associate applications with a group, such as wikis, if they are available for your deployment. When you do this, a link and a feed to the parent wiki page are provided in the group\'s overview page. Group membership is automatically synchronized with the wiki. Deleting the group also deletes the application.',
'label.side.left.alpha': 'Alphabetical',
'multiFeedReaderUpdatedBy': 'updated by:',
'label.communityProfile': 'Group Profile',
'label.theme.addwidget': 'Add Content',
'label.footer.help': 'Help',
'tools.add.bookmarklet.title': 'Add to group Bookmark Button',
'label.footer.home': 'Home',
'hideWidget': 'Hide Widget',
'message.findmembers.error': 'An error occurred while performing your search.',
'feedreader.feeds.membernocontent': 'Stay current with up-to-minute information.',
'error.message.wrongemailinvitation': 'Sorry, the e-mail associated with the user ID you signed in with does not match the e-mail used for your invitation to join a group.<br/><br/>To accept the invitation to join the group, please contact the person who sent you the invitation so that you can either update the e-mail address in your profile, or ask the sender to use a different e-mail address for you.',
'errors.invalid': '{0} is invalid.',
'link.seeall.param': 'See all ({0})',
'tools.rtclick1r': 'Right-click this button',
'error.title.invalid.uri': 'The bookmark or feed URL is invalid.',
'search_refineSearch': 'Refine search options',
'atom.app.community.managed.apps.title': '{0} Remote Applications',
'label.form.feed.edit': 'Edit Feed',
'errorStackTrace': 'Trace: ',
'str.join.community.nonce.action': 'join group: "{0}" ',
'SAVE': 'Save',
'error.upload.virus.error': 'Virus scan error: {0}',
'label.tagcloud.title.tags': 'Tags for {0} with tag {1}',
'tools.toolbar.button': 'Bookmark Toolbar Button',
'ERROR_TOOMANYSELTAGS': 'Please select up to 5 tags',
'Members': 'Members',
'Forum': 'Message Board',
'invite.label.custom.message': 'Custom message (Optional):',
'tools.rtclick2r': 'Right-click the "<b>Add to group</b>" button.</li>',
'label.request.time': 'Request took {0} secs',
'invite.label.to.info': 'Maximum 10 e-mail addresses, separated by commas',
'mydw.breadcrumb.url': '//www.ibm.com/developerworks/',
'tools.firefox.users.instructions': 'Drag the image below to your bookmarks toolbar.',
'label.form.tips.booktags': 'Tags are keywords that describe the content of the bookmark link. They also help users to find bookmarked content. Tags must be a single word or multiple words connected with underscores or hyphens. ',
'tools.dragthis': 'Drag this button to your <br/> browser\'s links toolbar.',
'confirm.added.member': 'You have successfully added {0} to this group.',
'label.theme.com.changetheme': 'Change the theme of your group',
'label.top.login': '',
'invite.label.from': 'From: ',
'label.moderated.community.type.text': 'Moderated',
'info.feed.specific.bad.format': 'The feed XML has errors - check with feed provider',
'confirm.requesttojoin': 'Your membership request has been sent.',
'label.top.buttons.delete': 'Delete Group',
'label.action.confirm.community.before.leave': 'Leaving this group will remove you from the membership.',
'error.title.generic': 'We\'ve encountered a problem.',
'label.theme.name.midnightgrey': 'Midnight Grey',
'label.form.topic.reason.info': 'You may enter a reason for the deletion (optional):',
'link.next': 'Next',
'atom.app.communities.my.title': 'My Groups',
'button.ok': 'OK',
'label.forum.discussion.threaded': 'Threaded View',
'label.theme.name.brushedmetal': 'Brushed Metal',
'info.virus.scanning.error': 'Communication error during virus scanning - {0}',
'label.form.community.edit': 'Edit a Group',
'str.remove.member.nonce.action': 'remove member: {0} from group: "{1}"',
'label.forum.topics.wait': 'Please wait while the topics are loading...',
'label.add.members': 'Members:',
'ERROR': 'Error! Widget is unable to retrieve data',
'tips.tags.blogs': 'A tag is a keyword that you assign to a blog to categorize it and make it easy to find. Type or click a tag to see the blogs associated with it. Popular tags appear in larger, darker text in the tag cloud or list. Use the slider to control how many tags display.',
'err.virus.detected': 'Virus detected - {0}',
'label.sort.by.filter': 'Sort by:',
'label.top.search.alt': 'Search',
'error.basicauth.nodispatcher': 'Unable to find request dispatcher for servlet: {0}',
'label.community.all.search.results': '<a href="{0}">Public Groups</a> matching {1}',
'search.allcommunities': 'Public Groups',
'tips.tags.content.feeds': 'A tag is a keyword that you assign to a feed to categorize it and make it easy to find. <br/>Type or click a tag to see the feeds associated with it. <br/>Popular tags appear in larger, darker text in the tag cloud or list. <br/>Use the slider to control how many tags display.',
'label.side.right.bookmarks': 'Important Bookmarks',
'button.send': 'Send',
'CANCEL': 'Cancel',
'err.feed.authentication.required': 'Authentication required',
'label.popup.closeHelp': 'Close Help',
'tips.tags.content': 'A tag is a keyword that you assign to a group to categorize it and make it easy to find. <br/>Type or click a tag to see the groups associated with it. <br/>Popular tags appear in larger, darker text in the tag cloud or list. <br/>Use the slider to control how many tags display.',
'confirm.removed.multiple.forum.topics': 'You have successfully removed {0} forum topics from this group.',
'errors.detail': '{0}',
'label.forum.discussion.less': '... [less]',
'atom.app.community.feeds.title': '{0} Feeds',
'Files': 'Files',
'error.charfilter.characterencode': 'Error setting character encoding to: {0}',
'tooltip.members': 'Click here to see the group&#146;s members',
'label.member.lowercase': 'member ',
'label.pagestatistics': 'Statistics for this page',
'mydw.breadcrumb.url2': 'http://www.ibm.com/developerworks/community',
'label.about.find.header': 'Find Out More...',
'label.top.buttons.leave': 'Leave Group',
'label.feed.confirm.add': 'The feed has been added to your group.',
'label.share.this': 'Share%20this',
'TITLE': 'Title',
'tab.mycommunities': 'My Groups',
'label.communities.your.tag': 'My {0} groups',
'label.action.confirm.invite.sent': 'Your invitation has been sent',
'email.body.headline': 'would like to share this group with you:',
'label.theme.name.emeraldgreen': 'Emerald Green',
'label.footer.bookmarkplugins': 'Bookmark Browser Plug-ins',
'label.footer.accesibility': 'Accessibility Tools',
'edit': 'Edit',
'tools.add.bookmarklet.description': 'Bookmark buttons are links you add to your browser\'s "Links" toolbar. This button allows you to post your current Web page to a group. Select text on the Web page to use as the bookmark description.',
'label.side.left.start.bold': '<b>Start</b> a group',
'label.private.community.alt.text': 'This is a restricted group',
'feedreader.updatedby': 'Updated by',
'label.delete': 'Delete',
'feedreader.feeds.nocontent': 'There are no feeds yet for this group.',
'label.members.lowercase': 'members ',
'tools.add.addto': 'Add to group',
'label.form.member.edit': 'Edit Members',
'confirm.removed.multiple.members': 'You have successfully removed {0} members from this group',
'error.message.managed.app.update.failed': 'An operation on an associated application could not be completed.  A remote service may be unavailable.  Contact your system administrator.',
'label.forum.topics.topic': 'Topic:',
'email.body.description': 'Description of the group:',
'label.communities.withparams': 'Groups: ',
'err.feed.specific.bad.format': 'Error with the feed formatting',
'confirm.removed.members': 'You have successfully removed the following people from this group: {0}.',
'email.body.vlink': '/developerworks/mydeveloperworks/groups/service/html/communityview?communityUuid=',
'email.body.from': 'From',
'label.meta.metaKeywords': 'Groups, Rational, WebSphere, DB2, Informix, Information Management, IBM Systems, Lotus, Tivoli, Autonomic computing, Grid computing, Java, XML, Linux, open source, Web architecture, SOA, Web services, Wireless, Power Architecture, Multicore acceleration, tutorials, training, online courses, howto, tips, tools, code, education, forums, blogs, articles, events, Webcasts, technical briefings, downloads, best practices, developer, programmer, system administrator, architect, computer programming resources, developer resources, software development, application development, free programming training, free programming tutorials, programming how to, components, objects, ondemand business, Software Development Platform',
'widgetCat_thrdParty': 'Other',
'NFLUENT_WIDGET_INFO': '<b>Real-Time Translation</b> performed by IBM n.Fluent.',
'str.update.community.nonce.action': 'post changes to group: "{0}" ',
'search.advanced': 'Advanced',
'hostname': 'https://www.ibm.com',
'label.use.email.client': 'Click to send using your favorite e-mail client',
'communities.metric.totals.communities': 'Total number of groups',
'label.dispcom.by': 'by',
'label.forum.discussion.more': '... [more]',
'email.body.jointext.public': 'Join now by accessing the URL below',
'err.virus.replaced': 'Viral content replaced',
'error_serverDown': 'The Application Server can not be reached',
'close': 'Close',
'label.stats.title': 'Groups Server Statistics (since last server restart)',
'label.about.demo': 'Watch demo',
'label.for.person.tag': '{2} groups for <a href="{0}">{1}</a>',
'label.broadcasts': 'Broadcasts',
'label.associated.apps': 'Associated Applications',
'Feeds': 'Feeds',
'errors.token': 'The request could not be completed. The operation is not in sequence.',
'label.meta.ibmWTMCategory': 'SOFDCGRPZZ',
'label.top.buttons.actions': 'More Actions',
'Activities': 'Activities',
'error.title.toolarge.community.desc': 'The group description is too large; this field is currently {0}% larger than its limit. ',
'label.bookmark.add.important': 'Add to Important Bookmarks',
'CUSTOM_WIDGET_EDIT_INFO': 'Use this widget to promote important content to your group members.<br/><ul><li id="liststyle">Please use a unique title for your widget (75 characters or less).</li><li id="liststyle">Make sure that any images, tables, or inline frames containing other documents are less than 550 pixels wide.</li></ul>',
'label.side.left.leave': 'Leave this group',
'label.last.feeds': 'Last {0} Feeds',
'label.icon.moderated': 'moderated',
'about.copyright': 'Licensed Materials - Property of IBM, 5724-S68 &#169; Copyright IBM Corporation 2007, 2009. All Rights Reserved. IBM, the IBM logo, ibm.com and Lotus are trademarks of IBM Corporation in the United States, other countries, or both. Java and all Java-based trademarks are trademarks of Sun Microsystems, Inc. in the United States, other countries, or both. Other company, product, or service names may be trademarks or service marks of others.  A current list of IBM trademarks is available on the Web at www.ibm.com/legal/copytrade.shtml.  U.S. Government Users Restricted Rights:  Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp.  This Program is licensed under the terms of the license agreement accompanying the Program.  This license agreement may be either located in a Program directory folder or library identified as "License" or "Non IBM License", if applicable, or provided as a printed license agreement. Please read this agreement carefully before using the Program. By using the Program, you agree to these terms.',
'label.top.buttons.join': 'Join this Group',
'label.tagcloud.title': 'Tags for {0}',
'multiFeedReaderSeeAllFeeds': 'See all the entries',
'label.theme.form.hdr1': 'Customize your Group Design',
'label.form.member.add': 'Add Members',
'label.theme.form.hdr2': 'Click on one of the Themes below to change your page design...',
'feedreader.bookmarks.logo': 'Bookmarks logo',
'invite.button.send': 'Send',
'widgetPalette': 'Widget Palette',
'search.wiki': 'Wikis',
'tools.safari.step1': 'Step 1: Add the bookmark bar button',
'label.addtocommunity': 'Add to group',
'label.private.community': 'This group does not allow public access.',
'label.form.bookmark.add': 'Add Bookmark',
'error.title.empty.community.name': 'The group name must not be empty.',
'label.forum.topics.reason': 'Reason for deletion:',
'confirm.delete.forum.topic': 'Are you sure you want to delete this topic? ',
'label.banner.about': 'About',
'error.title.toolarge.ref.desc': 'The bookmark or feed description is too large.',
'label.side.left.start': 'Start a group',
'label.feed.hide.details': 'Hide details',
'err.feed.general': 'Unable to retrieve the feed',
'email.body.jbutton.lable': 'Join now',
'atom.error.methodNotAllowedOnCollection': 'This collection does not support the specified HTTP method.',
'label.form.tips.bookimp': 'The Important Bookmarks list displays on the group\'s overview page. You can use this list to share key Web links with other members of your group.',
'atom.app.communities.all.title': 'Public Groups',
'label.feed.show': 'Click here to show entries',
'str.delete.community.nonce.action': 'delete group: "{0}" ',
'label.request.membership': 'Request Membership: {0}',
'error.exhandler.nohandler': 'No exception handler has been defined for this web context.',
'label.feed.confirm': 'Are you sure you want to delete this feed? ',
'communities.metric.private.communities': 'Total number of restricted groups',
'label.collapse': 'Click to collapse section',
'widgetCat_hidden': 'Hidden',
'email.addgroup.members': '<b><a href="{notification.sender.profilelink}">{notification.sender.name}</a></b> sent the following message to all members of the My developerWorks group: <a href="{community.url}">{community.name}</a><br /><br />',
'label.theme.name.corporate': 'Corporate Theme',
'label.all.feeds': 'View all feeds',
'feedreader.bookmarks.membercreatefirst': 'Add your first bookmark',
'LOADING': 'Loading...',
'commBookmarks': 'Use this widget to link to key Web resources from your group.',
'search_searchFor': 'You searched for {0}',
'communities.metric.distinct.owners': 'Total number of distinct owners',
'search.profile': 'Profiles',
'label.metrics.title': 'Groups Metrics',
'label.forum.topics.title': 'Title:',
'label.forum.topics.posted': 'Posted by:',
'errorType': 'Type: ',
'label.bookmark.add': 'Add Bookmark',
'label.side.left.alpha.alt': 'Shows the groups in alphabetical order',
'tooltip.home': 'Click here to see the group&#146;s home page',
'label.form.topic.delete': 'Delete Entry',
'widget_AddingWidget': 'Adding Widget',
'label.welcome.info3.old': 'Make sure to fill in the basics that make it clear what your group is all about. Import a graphic to give a personal look. Add bookmarks to link your group to resources or articles. Drag the Bookmark button to your toolbar for easy access.',
'label.top.buttons.com.actions': 'Group Actions',
'label.edit': 'Edit',
'label.all.bookmarks': 'View all bookmarks',
'label.about.help': 'Help',
'label.home': 'Home',
'errors.creditcard': '{0} is not a valid credit card number.',
'label.recipientType': 'To:',
'email.body.end.logintext': 'When you join this group, you may be asked to log in with your IBM ID and password, or register to create an ID and password.',
'NFLUENT_WIDGET_EDIT_HEADING': 'Select the primary language for the content of your group',
'deleteWidgetMsg': 'You are about to remove your widget. This will remove all widget content from the application. This action cannot be undone.<br/><br/>If you are sure you want to remove the widget, click the Remove button below. <br/>Otherwise, click Cancel.',
'link.last': 'Last',
'link.first': 'First',
'label.tags': 'Tags:',
'communities.metric.public.communities': 'Total number of public groups',
'label.feed.help1': 'To subscribe to a feed, look for this icon: ',
'tips.bookmarks': 'Group members can contribute bookmarks to Web sites of interest to the group. Group members can flag important bookmarks so that they stand out.',
'label.feed.help2': 'Right click it, copy the link location, and then paste it into the field below.',
'atom.error.memberNotPartOfCommunity': '{0} is not a member of the specified group.',
'tools.firefox.users': 'Firefox users:',
'label.confirm.icon.alt': 'Confirm icon',
'label.owners.only': 'Owners',
'label.orderedlist': 'Ordered list',
'label.page': 'Page ',
'multiFeedReaderNoFeeds': 'No feeds available',
'message.leave.noaccess': 'You have successfully left the group.  By leaving, you are no longer permitted to view that group or its resources.',
'label.form.topic.reason': 'Reason (optional):',
'label.error.icon.alt': 'Error icon',
'confirm.already.member': 'You were already a member of this group.',
'label.banner.tools': 'Tools',
'error.title.notauthorized': 'We\'ve encountered a problem.',
'label.top.scope.alt': 'Search scope',
'label.about.footer': 'Footer',
'ERROR_MUSTSELTAG': 'Please select a tag',
'label.footer.rest.help': 'REST API Help',
'errors.required': '{0} is required.',
'CUSTOM_WIDGET_INIT_MSG': 'The possibilities are endless. Customize this group with HTML.',
'errorName': 'Name: ',
'label.search.directory': 'Search Directory for',
'label.community.delete': 'Delete group',
'widgets_Move': 'Move',
'warn.missing.email': '{0} lacks an e-mail address and will not receive this message via e-mail.',
'SAVING': 'Saving...',
'tooltip.overview': 'Click here to see the group&#146;s overview page',
'error.title.server.down': 'The Groups service is temporarily unavailable.',
'delete': 'Delete',
'label.bookmarks': 'Bookmarks',
'popup.recent.bookmarks': 'These are the most recent bookmarks added to the group. Any group member can add a bookmark to the group.',
'feedreader.feeds.logo': 'Feeds logo',
'label.side.left.popular.alt': 'Shows the groups with the most members',
'label.footer.demo': 'Watch a Demo',
'widget_RemovingWidget': 'Removing Widget',
'label.compose.email': 'Send an e-mail message to the group',
'error.title.toolarge.community.name': 'The group name is too long.',
'label.footer.support': 'Lotus Support Forums',
'errors.minlength': '{0} cannot be less than {1} characters.',
'VIEW': 'View',
'communities.metric.login30days.users.desc': 'Total number of distinct logged in users in the last 30 days',
'atom.error.invalidRequest': 'Invalid request.',
'tools.rtclick1': 'Click this button',
'tools.rtclick2': 'Click the "<b>Add to group</b>" button.</li>',
'label.for': '{0} for {1}',
'label.about.box1': 'Provide a meeting of the minds',
'errors.label.support.forum': 'Groups Support Forum',
'label.about.box2': 'Groups are groups of people with a common interest. A public group is available for all to join, while a restricted group is restricted to a particular group. A group provides a central spot for users to stay in touch, share information, and exchange ideas.',
'label.addtocommunity.bookmark': 'Add to groups bookmarklet',
'error_deleteWidgetPending': 'This widget is pending deletion',
'atom.app.community.members.title': '{0} Members',
'link.add.members': 'Add Members ...',
'label.footer.json': 'JSON',
'tools.step2B': 'Step 2: Set up your bookmark form',
'message.findmembers.toomanyresults': 'Too many results found. Please refine your search further.',
'label.open.communities': 'Groups',
'errorUnableToConnect': 'Connection failed for {0}',
'warn.missing.emails': '{0} people ({1}) lack e-mail addresses and will not receive this message via e-mail.',
'feedreader.viewallparam': 'View All ({0})',
'confirm.delete.member': 'Are you sure you want to delete this member?',
'label.form.topic.add': 'Post Topic',
'communities.metric.login24hr.users': 'Number of users logged in today',
'multiFeedReaderPostedBy': 'posted by:',
'error.title.invalidchar.tag': 'Tags can contain only alphanumeric characters (a-z, A-Z, and 0-9), international characters, and the following special characters: apostrophe (\'), at sign (@), colon (:), comma (,) hyphen (-), left parenthesis ((), number sign (#), period (.), right parenthesis ()), slash (/), space ( ), and underscore (_).',
'errors.date': '{0} is not a date.',
'label.forum.topics.edit': 'Edit',
'atom.error.invalidAtomEntry': 'Invalid entry.',
'label.pagenumber': 'Page {0}',
'label.addparam.community': 'Add {0} to group',
'confirm.delete.community': 'Are you sure you want to delete this group? Deleting this group will remove all data including any content that has been added to the group. Click OK to delete this group or Cancel to return to the group. ',
'label.community': 'Group:',
'error.title.toolong.tag': 'One of the specified tags is too long and must be reduced in size. Please select a shorter tag title.',
'communities.metric.login30days.users': 'Number of users logged in the last month',
'label.photo.title': 'Group logo',
'errors.invalid.username.password': 'Invalid username or password...',
'label.card.more': 'more...',
'label.last': 'Last page',
'tools.rtclick7': 'If your "Links" toolbar is not visible, select it via the "<b>View->Toolbars</b>" menu.</li>',
'tools.rtclick6': 'Click "<b>OK</b>".</li>',
'confirm.modified.members': 'You have successfully updated the following people in this group: {0}.',
'tools.rtclick5': 'Select the "<b>Links</b>" folder in the dialog box.</li>',
'tools.rtclick4': 'When asked "You are adding a favorite that may not be safe. Do you want to continue?", click "<b>Yes</b>".</li>',
'tools.rtclick3': 'Select "<b>Add to Favorites</b>".</li>',
'button.cancel': 'Cancel ',
'error.message.session.validation': 'Click OK to complete this action: {0}',
'label.form.tips.bookurl': 'The URL is the Web address of the resource you want to bookmark. This is a required field. If the link changes, you can update it using the Edit Bookmark form.',
'error.message.missing.link': 'The page you are looking for could not be found. The page might have been deleted or moved, or you might have mistyped the URL. Check the link and try again.',
'label.bookmark.empty.important': 'Highlight key Web resources.',
'search.allareas': 'All My developerWorks',
'error.image.upload.error': 'Error occurred while attempting to upload or resize the group image.',
'label.theme.changetheme': 'Change Theme',
'label.login.error.image.title': 'Error',
'label.banner.feedback': 'Feedback',
'label.login.pass': 'Password:',
'str.add.member.nonce.action': 'add people to group: "{0}" ',
'label.expand': 'Click to expand section',
'str.mail.community.nonce.action': 'send a mail message to group: "{0}" ',
'tooltip.feeds': 'Click here to see the group&#146;s feeds',
'label.welcome.info4': 'Get people involved by starting a discussion in the group forum. Set up a feed to pull in content updates from relevant Web sites. Add widgets to make extra functionality available to members.',
'multiFeedReaderLoading': 'Loading feed...',
'INFO_OWNER_NOTAG': '<p>No keyword tags have been identified. Select "Edit" to learn more.</p>',
'atom.app.communities.title': 'Groups Collections',
'label.login.error': 'Your user name and/or password does not match any existing accounts. Please check and try again.',
'tab.allcommunities': 'Public Groups',
'CUSTOM_WIDGET_DEFAULT_TITLE': 'Custom HTML',
'feedreader.bookmarks.membercreate': 'Add a bookmark',
'atom.app.community.bookmarks.title': '{0} Bookmarks',
'label.side.left.recent.alt': 'Shows the groups with the most recent activity',
'invite.label.invite.form.title': 'Invitation to join this group:',
'label.side.left.popular': 'Popular',
'tools.safari.dragthis': 'Drag this button to your <br/> browser\'s bookmarks bar.',
'tooltip.managed.apps': 'Click here to see the group&#146;s managed applications',
'label.welcome.info3': 'Be sure to fill in the basics to make it clear what your group is all about. Import a graphic or apply a theme to give the group a personal look. Share links to relevant Web resources. ',
'label.welcome.info2': 'Use your new group to share information and raise awareness about your topic. ',
'label.welcome.info1': 'Get Started!',
'errorLine': 'Line:',
'tips.community': 'Use the overview to keep track of the latest updates to your group. ',
'feedreader.viewall': 'View All',
'str.request.to.join.community.nonce.action': 'request to join group: "{0}" ',
'label.members': 'Members',
'label.tools': 'Tools',
'invite.button.cancel': 'Cancel',
'filesDescription': 'Use this widget to share files with your group.',
'str.add.reference.nonce.action': 'add link: "{0}" to group: "{1}" ',
'label.forum.topics': 'Topics',
'search.thisCommunity': 'This Group',
'link.add.owners': 'Add Owners',
'label.top.com.name': 'Group Name',
'tips.feeds': 'Feeds pull information from a Web site into a group so that members can stay informed without leaving the group page. Add a feed to provide up-to-the-minute news to your group members.',
'label.private.community.type.text': 'Restricted',
'errorDefaultMsg': 'Unable to display widget data',
'label.footer.about': 'About',
'EDIT': 'Edit',
'label.all.members': 'Members',
'search.files': 'Files',
'atom.error.unknownUser': 'Unknown user.',
'blogsDescription': 'Use this widget to add a blog to your group for members to contribute.',
'errors.prefix': '',
'label.forum.topics.recent': 'Recently updated topics',
'label.form.tips.feedtags': 'Tags are keywords that describe the content of a feed. Tags must be a single word or multiple words connected with underscores or hyphens. ',
'EDIT_INFO_HEADING': 'Tags for related content',
'error.failedToRemove.members': 'You have failed to remove the following people from this group: {0}.',
'label.forum.topics.response': 'Post Reply',
'err.feed.specific.no.feed.data': 'There is no feed at the specified URL',
'label.openactivities': 'Groups',
'label.feed.show.details': 'Show details',
'label.editCommunity': 'Edit Group',
'link.add.members2': 'Add Members',
'label.stats.name': 'Name',
'str.update.reference.nonce.action': 'post changes to link: "{0}" in group: "{1}" ',
'label.subscribe.feed.mycom': 'Feed for My Groups',
'label.underline': 'Underline',
'label.description': 'Description:',
'label.forum.discussion.replycnt1': '{0} reply',
'err.feed.forum.general': 'Unable to retrieve the Forum feed',
'link.window.close': 'Close window',
'email.body.jlink.moderated': '/developerworks/mydeveloperworks/groups/service/html/requestmembership?returnto=communityview&communityUuid=',
'label.community.my.search.results': '<a href="{0}">My Groups</a> matching {1}',
'label.subject': 'Subject:',
'invite.text.invite.subject': 'wants you to join this group: ',
'error.method.not.allowed': 'Method not allowed',
'commActivitesDescription': 'Use this widget to create activities to track group goals and assign to-dos.',
'NFLUENT_WIDGET_EDIT_INFO': 'For the primary language, select the language that you anticipate most of your group using. Users will then be able to translate your group from English into 11 other languages or from one of those languages into English.',
'label.postedby': 'Posted by',
'errors.maxlength': '{0} cannot be greater than {1} characters.',
'label.about.tips.info2': 'Select a tag to show a filtered list of groups that relate to a particular topic.',
'label.about.tips.info1': 'When you start a group, make it clear what kind of a group you are forming.',
'atom.error.duplicateReferenceUri': 'A reference to the specified URI already exists in the group.',
'label.about.tips.info4': 'When you create a group, you can set up feeds to maintain a current set of information to keep group members informed. Group members have the option of subscribing to the feed.',
'label.about.tips.info3': 'The Public Groups view displays all the public groups you can view. The My Groups view lists the groups you belong to.',
'tools.safari.toolbar.button': 'Bookmark Bar Button',
'atom.error.lastCommunityOwner': 'The last owner of a group may not leave.  There must be at least one group owner.',
'label.email.sent': 'Your mail was sent successfully.',
'label.action.confirm.community.after.leave': 'You have left this group and are no longer a member',
'label.forum.discussion.recent': 'Recent Post View',
'label.login.lacks.email': 'Users must have a valid email address.  Contact your system administrator for assistance.',
'label.forum.topics.deleted': 'This entry has been deleted',
'info.feed.specific.no.feed.data': 'Please check the feed URL',
'label.alt.moderated': 'This is a moderated group',
'label.bookmark.confirm': 'Are you sure you want to delete this bookmark? ',
'hide': 'Hide',
'label.community.tags': 'Group tags:',
'login.message.heading': 'What can you do with Groups?',
'error.failToModify.members': 'You have failed to update the following people in this group: {0}',
'label.footer.connections': 'Lotus Connections',
'error.title.managed.app.update.failed': 'Failed to create or update an associated application.',
'link.prev': 'Previous',
'label.form.topic.edit': 'Edit Entry',
'label.feed.tags': 'Feed tags:',
'feedreader.bookmarks.membernocontent': 'Share Web resources with your group.',
'communities.metric.private.communities.desc': 'Number of restricted groups.',
'label.theme.name.deepblue': 'Deep Blue',
'label.forum.topic': 'Topic',
'multiFeedReaderCreatedBy': 'created by:',
'label.searchresults.noresults': 'No results were found for that search.',
'err.virus.uploaded': 'The file you uploaded contains a virus',
'tips.tags.forums': 'A tag is a keyword that you assign to a forum to categorize it and make it easy to find. Type or click a tag to see the forums associated with it. Popular tags appear in larger, darker text in the tag cloud or list. Use the slider to control how many tags display.',
'label.addto.confirm': 'The bookmark has been added to your group.',
'label.about.tips': 'Tips',
'label.show': 'show',
'email.addgroup.owners': '<b><a href="{notification.sender.profilelink}">{notification.sender.name}</a></b> sent the following message to all owners of the My developerWorks group: <a href="{community.url}">{community.name}</a><br /><br />',
'label.action.confirm.mail.sent': 'Your mail has been sent',
'widget_AllTab': 'All',
'link.atom.publish.protocol': 'Atom Publishing Protocol',
'label.subscribe.feed.members': 'Feed for Group Member List',
'label.feed': 'Feed:',
'label.moderated.community.alt.text': 'This is a moderated group',
'communities.metric.public.communities.desc': 'Number of public groups.',
'label.about.transcript': 'Click here to read a text transcript of this tutorial',
'str.msgid.ignore': 'true',
'email.body.jointext.moderated': 'Request to join now by accessing the URL below',
'link.seeall': 'See all',
'error.message.invalidCharInMembers': 'The members list you entered contains invalid characters such as \'?\' and \'*\'.  Please remove these characters from the member list.',
'popup.subscribe.to.feed': 'Please right click and select Copy Shortcut to get the URL to this feed.',
'forumDescription': 'Give your group a place to discuss topics and share ideas.',
'label.about.othertools': 'Other networking tools from IBM',
'label.community.edit': 'Edit group',
'label.theme.changestyles': 'Change Styles',
'email.body.jlink': '/developerworks/mydeveloperworks/groups/service/html/communityaddmeaction?communityUuid=',
'label.login.button': 'Log In',
'label.request.instructions': 'All membership requests for this group require approval from a group owner. <p> <p> Please tell the group owner why you would like to join this group.  Click the "Send" button and your request will be sent.',
'label.form.tips.feed': 'You can subscribe to a feed to make content from a particular Web site available to group members without having to leave Groups. The Feed field identifies the Web location of the feed you want to subscribe to. If the link changes, you can update it using the Edit Feed form.',
'error.message.database.unavailable': 'The database server is unavailable or database creation/migration scripts need to be run.',
'label.insert.link': 'Insert Link',
'error.title.community.doesnotexist': 'The group which this resource or page is associated with does not exist.',
'error.message.duplicate.email': 'Another user has the same email address.  Contact your system administrator. ',
'label.header.search': 'Search',
'label.clearSearch': 'Clear search results',
'errors.header': '<div class="errorMessages">',
'errors.label.back.to.dashboard': 'Back to the My Groups view',
'confirm.added.multiple.members': 'You have successfully added {0} members to this group.',
'label.about.find': 'Find out more',
'label.forum.discussion.replycnt': '{0} replies',
'atom.gen.error.loadAtomLinks': 'Error loading atom links properties file',
'label.welcome.info1.old': 'Get Started!',
'label.about.faq': 'Frequently asked questions',
'label.forum.topics.actions': 'More Actions',
'errors.general': 'The process did not complete. Details should follow.',
'label.remove': 'remove',
'login.message': 'Join or organize a group around a common interest. Use bookmarks and feeds to keep your group informed.',
'mydw.breadcrumb.second': 'Community',
'label.hide': 'hide',
'label.footer.connectionsweb': 'Lotus Connections on ibm.com',
'error.title.duplicate.ref': 'That bookmark or feed has already been entered.',
'label.feed.hide': 'Click here to hide entries',
'label.footer.tools': 'Tools',
'confirm.delete.community.original': 'Are you sure you want to delete this group?',
'errors.range': '{0} is not in the range {1} through {2}.',
'label.metrics.dataErrMsg': 'Data Error ',
'search.blogs': 'Blogs',
'label.release': 'Release {0}',
'search.dogear': 'Bookmarks',
'tips.tags.content.blogs': 'A tag is a keyword that you assign to a blog to categorize it and make it easy to find. <br/>Type or click a tag to see the blogs associated with it. <br/>Popular tags appear in larger, darker text in the tag cloud or list. <br/>Use the slider to control how many tags display.',
'label.feed.icon': 'Download feed',
'email.body.or': 'Or',
'label.community.get.started': 'Get started with this group!',
'error.no.subject': 'Please enter a subject.',
'confirm.removed.forum.topic': 'You have successfully removed a forum topic from this group.',
'label.italic': 'Italic',
'tools.step1': 'Step 1: Add the toolbar button',
'tips.tags.bookmarks': 'A tag is a keyword that you assign to a bookmark to categorize it and make it easy to find. Type or click a tag to see the bookmarks associated with it. Popular tags appear in larger, darker text in the tag cloud or list. Use the slider to control how many tags display.',
'tools.step2': 'Step 2: Create bookmarks ',
'tools.step3': 'Step 3: Create bookmarks',
'error.image.notfound.error': 'The group image was not found.',
'error.title.last.owner.leave': 'The last owner may not leave a group.',
'tooltip.forum': 'Click here to see the group&#146;s discussion forum',
'Bookmarks': 'Bookmarks',
'label.metrics.asof': 'As of: ',
'label.side.left.email': 'Mail this group',
'label.tagcloud.title.my': 'Tags for My Groups',
'feedreader.bookmarks.nocontent': 'There are no bookmarks yet for this group.',
'label.form.discussion.add': 'Post Reply',
'link.browse': 'Browse...',
'label.feed.safari.help2': 'Right click it, copy the link, and then paste it into the field below.',
'confirm.join': 'You are now a member of the group.',
'str.leave.community.nonce.action': 'leave group: "{0}" ',
'communities.metric.publicinvite.communities.desc': 'Total number of public invite only groups',
'tools.ie.users': 'Internet Explorer users:',
'atom.error.duplicateCommunityName': 'A group with the requested name already exists, choose a different name and resubmit.',
'label.feeds': 'Feeds',
'str.delete.reference.nonce.action': 'delete link: "{0}" from group: "{1}" ',
'errors.footer': '</div>',
'label.alt.private': 'This is a restricted group',
'label.tag.filter': 'With tag:',
'error.title.toolarge.ref.name': 'The bookmark or feed name is too long.',
'label.addto.bookmark': 'Add a bookmark to your group',
'label.subscribe.feed.bookmarks': 'Feed for Group Bookmark List',
'email.body.start': 'My developerWorks [Groups]',
'invite.label.to': 'To:',
'tooltip.broadcasts': 'Click here to see the group&#146;s broadcasts',
'commFeeds': 'Use feeds to pull the latest information from relevant Web sites in to your group.',
'error.title.userNotFound': 'The user cannot be found.',
'errors.label.tap.homepage': 'Groups home page on TAP',
'label.top.com.desc': 'Group Description',
'label.private': 'Restricted:',
'error.title.session.validation': 'Confirmation Required.',
'error.noLogoutUrl': 'The \'com.ibm.connections.communities.web.ui.logoutServlet\' servlet context parameter must be set in order to perform a logout.',
'atom.app.community.collections.title': '{0} Collections',
'error.title.mail.failure': 'Failure sending e-mail. The mail server may be down.',
'label.subscribe.feed.allcom': 'Feed for Public Groups',
'label.form.bookmark.edit': 'Edit Bookmark',
'refresh': 'Refresh',
'label.form.discussion.edit': 'Edit Entry',
'Wiki': 'Wiki',
'CUSTOM_WIDGET_EDIT_INFO_HEADING': 'Content for custom widget',
'label.background.color': 'Background Color',
'error.message.server.down': 'Groups is closed for maintenance. Groups should be up and running shortly - check the support forum for updates on the server status.',
'help': 'Help',
'label.theme.customize': 'Customize',
'str.create.community.nonce.action': 'create group: "{0}" ',
'label.body': 'Message:',
'widget_BackToOverview': 'Back to Overview Page',
'label.meta.owner': 'dW Information/Raleigh/IBM',
'label.form.tips.comtags': 'A tag is a descriptive term or keyword that you can assign to a group to identify what the group is all about. Tags must be a single word or multiple words connected with underscores or hyphens. ',
'error.title.duplicate.community': 'A group by that name already exists.',
'label.public.community': 'This group allows public access, and anyone can join.',
'label.community.members': 'Members:',
'label.photo.remove': 'Remove image',
'label.first': 'First page',
'label.bookmark.tags': 'Bookmark tags:',
'label.feed.add': 'Add Feed',
'errors.short': '{0} must be a short.',
'label.forum.discussion.breadcrumb': 'You are in: ',
'label.theme.name.royalpurple': 'Royal Purple',
'label.unorderedlist': 'Unordered list',
'tools.ie.users.instructions': 'Right-click the image below and add it to the "Links" folder in your favorites.',
'label.metrics.value': 'Value',
'errors.float': '{0} must be an float.',
'label.top.all': 'All',
'errors.long': '{0} must be a long.',
'label.browse.bytags': 'Browse by tags:',
'str_component_id': 'CLFRM',
'label.top.com.tags': 'Group Tags',
'label.tags.list': 'list',
'errors.open.communities': 'Groups Error',
'feedreader.createdby': 'Created by',
'error.title.duplicate.email': 'Another user has the same email address.',
'error.title.server.failed.initialization': 'The Groups service is temporarily unavailable.',
'label.indent': 'Indent',
'search.activities': 'Activities',
'widgets_MoveUp': 'Move Up',
'label.login.info': 'Bring together people with common interests. Share bookmarks and feeds with group members.',
'email.body.vbutton.lable': 'Visit the community',
'tips.tags.comms': 'A tag is a keyword that you assign to a group to categorize it and make it easy to find. Type or click a tag to see the groups associated with it. Popular tags appear in larger, darker text in the tag cloud or list. Use the slider to control how many tags display.',
'label.public.invite.only.community': 'This group allows public access, but users must request to join. ',
'label.theme.name.darkbrown': 'Dark Brown',
'popup.allbkmrks.tags': 'Tags are keywords that are used to categorize the bookmarks in a group. Click a tag to see the bookmarks that are tagged with that keyword.',
'NFLUENT_WIDGET_FEEDBACK': 'Give us your feedback!',
'label.server.statistics': 'Groups Server Statistics',
'tips.tags.feeds': 'A tag is a keyword that you assign to a feed to categorize it and make it easy to find. Type or click a tag to see the feeds associated with it. Popular tags appear in larger, darker text in the tag cloud or list. Use the slider to control how many tags display.',
'label.form.community.add': 'Start a Group',
'errors.byte': '{0} must be an byte.',
'label.tips.forum': 'Use the discussion forum as a place to share ideas with others in the group, and to discuss topics of common interest.',
'label.forum.topics.message': 'Message:',
'tips.tags.content.forums': 'A tag is a keyword that you assign to a forum to categorize it and make it easy to find. <br/>Type or click a tag to see the forums associated with it. <br/>Popular tags appear in larger, darker text in the tag cloud or list. <br/>Use the slider to control how many tags display.',
'error.message.notauthorized': 'Sorry, the group page that you\'re trying to view is private and available only to group members.  If you want more information about the group, however, you could contact the group member who shared the group page link with you.  To join that group, you would need to be invited by the group owner.',
'error.title.empty.ref.name': 'The bookmark or feed name must not be empty.',
'label.bold': 'Bold',
'NFLUENT_WIDGET_EDIT_INFO_HEADING': 'Selecting the primary language',
'error.feed.load.general': 'An error occurred while attempting to load this feed.',
'communities.metric.distinct.users.desc': 'Number of people who are members of one or more groups. This number helps you to determine how many people are regular group members versus owners.',
'label.top.buttons.email': 'Mail Group',
'label.forum.discussion.return': 'Return to Topics List',
'label.welcome.safari.info3.old': 'Make sure to fill in the basics that make it clear what your group is all about. Import a graphic to give a personal look. Add bookmarks to link your group to resources or articles. Drag the Bookmark button to your bookmarks bar for easy access.',
'confirm.leave': 'You are no longer a member of the group.',
'info.feed.general.moreinfo': 'Click here to show more details',
'communities.metric.distinct.owners.desc': 'Number of people who are owners of one or more groups.',
'widgets_Min': 'Minimize',
'search_searchAgin': 'Search Again',
'error.title.database.unavailable': 'Database unavailable or not up-to-date.',
'communities.metric.distinct.users': 'Total number of distinct members',
'info.virus.scanning.result.ok': 'Content scanned - result OK',
'label.java.title': 'Sun Java',
'error.message.duplicate.ref': 'The bookmark or feed you are trying to add has already been added to this group. Hit the browser Back button to go back and try again. ',
'tools.create3': 'Fill in the information for your bookmark, select the group and click "<b>OK</b>".',
'label.forum.discussion.add': 'Reply',
'tools.create2': 'Click the "<b>Add to group</b>" button.',
'search_searchFor2': 'You searched for',
'tools.create1': 'Go to the site you want to bookmark.',
'label.recipientExpander': 'Click to show/hide the contents of the \'To\' field',
'label.welcome.learn': 'Learn more',
'label.join.allow': 'Allow people to Join the group',
'error.message.last.owner.leave': 'The last owner of a group may not leave.  Hit the browser Back button to go back and try again.  ',
'message.findmembers.invalidquery': 'Invalid query.',
'tips.tags.content.bookmarks': 'A tag is a keyword that you assign to a bookmark to categorize it and make it easy to find. <br/>Type or click a tag to see the bookmarks associated with it. <br/>Popular tags appear in larger, darker text in the tag cloud or list. <br/>Use the slider to control how many tags display.',
'atom.community.members.title': '{0} Members',
'.': '',
'search.mycommunities': 'My Groups',
'wikiDescription': 'Create a place where members can share information and work together.',
'label.about.coltwo1': 'Ready to share? Start a group!',
'label.about.coltwo2': 'Whether you are forming a project team, researching an emerging technology, or looking for people who share your love of a hobby, a group is a great way to reach out, get organized, and start sharing information. As a group owner, you can manage the content and membership for the group.',
'label.about.coltwo3': 'Give your group some personality',
'label.about.coltwo4': 'Import a logo or graphic to give your group the look you want. You might use a corporate logo to tie all groups together, or use unique graphics to visually identify each group. Change the colors and fonts used in your group by applying a theme. You can choose from the default themes provided or select a custom theme if custom themes are available.',
'label.browse.by': 'Browse by {0}:',
'ERROR_NOTAG': '<p id="red">You must add tags to your group to determine the content in this widget.</p><ul><li id="liststyle">Click Group Actions</li><li id="liststyle">Click Edit group</li><li id="liststyle">Enter tags in the field provided</li><li id="liststyle">Save and return to this widget to refine your tag selections</li></ul></p>',
'label.subscribe.feed.thisview': 'Feed for this view',
'label.remove.memeber.tool.tip': 'Click to remove this member from the group',
'tools.install.instructions': 'Installation instructions:',
'label.meta.description': 'On developerWorks Groups, IBMs resource for developers and IT professionals, access tools, code, training, forums, blogs, community, standards, IT samples, downloads and how-to documentation for Rational, WebSphere, Information Management, Lotus, Tivoli, AIX and UNIX, architecture, and Web development, plus open source development and cross-platform, open standards technologies including Java, Linux, XML, SOA and Web services, Autonomic computing, Multicore acceleration.',
'temp': 'temp'};var relWigId = {'GroupTagBlogFeeds': 'Related blog entries',
'HTMLWidget': 'Custom HTML',
'GroupTagMembers': 'Related profiles',
'GroupTagBookmarks': 'Related bookmarks',
'GroupTagGroups': 'Related groups',
'temp': 'temp'};