//   v3.4 06/01/2012
var GAAT40=typeof GAAT40=="undefined"||!GAAT40?{}:GAAT40;
GAAT40.main=function(a){GAAT40.hasRun=!1;GAAT40.NavigationHighlight=function(){this.subHeaderJson=subHeaderJson=GAAT40.SubheadingLUT;var c=document.location.pathname,b=function(b){typeof b!="string"?a(b).each(function(){var b=this;a(this.path).each(function(){c.toLowerCase().indexOf(this.value.toLowerCase())!=-1&&a("#"+b.id).addClass("gaat40-selected")})}):a("#"+b).addClass("gaat40-selected")};subHeaderJson!=null&&subHeaderJson!="undefined"?b(subHeaderJson.sub):b("gaat40-sbhdr_itc")};GAAT40.DropDown=
function(c,b){this.ddSelector=c;this.settings=b={minWidth:30};var d=a(c);this.resizeDropDowns=resizeDropDowns=function(){resizeHolder=function(d){d.each(function(){var d=b.minWidth,e=GAAT40.renderSettings.textDirection.indexOf("rtl")!=-1?c-a(this).parent().offset().left:a(this).parent().offset().left,f=40+a(this).prev().width();a(this).find("ul").each(function(){var b=a(this).width();e+d+b<c?d+=b:a(this).css("border","none");f>d&&(d=f)});a(this).width(d)})};var c=a(window).width();a(window).resize(function(){c=
a(window).width();resizeHolder(d)});resizeHolder(d)};var e=function(){var b,a,c=0;this.Add=function(d){if(GAAT40.Helper.IsIE6()&&d.find("iframe").length===0){a=d;b=d.html();var e=a.width(),f=a.height();d.wrapInner('<div style="z-index:1;position:relative;zoom:1"></div>');var g=GAAT40.renderSettings.textDirection.indexOf("rtl")!=-1?"right":"left";d.append('<iframe src="javascript:\'\'" frameborder="0" style="z-index: 0; position: absolute; top: 0; '+g+": 0; width: "+e+"px; height: "+f+'px !important;"></iframe>')}c++};
this.Remove=function(){c>0&&GAAT40.Helper.IsIE6()&&(a.html(b),c=0)}},f=function(){a(".gaat40-hover").removeClass("gaat40-hover")},g=function(b){var c=a(b).find(".gaat40-subsubnav"),d=c.width(),e=a(b).offset().left,f=a(b).offset().right,b=a(window).width();GAAT40.renderSettings.textDirection.indexOf("rtl");e=d+e+5;d=d+f+5;(GAAT40.renderSettings.textDirection.indexOf("rtl")!=-1?d:e)>b?c.css("right","-"+((GAAT40.renderSettings.textDirection.indexOf("rtl")!=-1?d:e)-b)+"px"):c.css("right","-1px")};resizeDropDowns();
GAAT40.Helper.Hide(d);(function(){var b=new e,i;d.parents("li").mouseover(function(){i&&(f(),clearTimeout(i));GAAT40.Helper.Hide(d.parents("li").find(c));a(this).find("a").eq(0).addClass("gaat40-hover");a(this).addClass("gaat40-hover");$thisLayer=a(this);g($thisLayer);b.Add(a(this).find(c));GAAT40.Helper.Show(a(this).find(c))}).mouseout(function(){f();$thisLayer=a(this);i=setTimeout(function(){GAAT40.Helper.Hide(d.parents("li").find(c))},5)});d.find("a").focus(function(){GAAT40.Helper.Hide(d.parent("li").find(c));
$thisLayer=a(this).parents(".gaat40-subsubnav").parents("li");$thisLayer.addClass("gaat40-hover");$thisLayer.find("a").eq(0).addClass("gaat40-hover");g($thisLayer);b.Add(a(this).parents(".gaat40-subsubnav"));GAAT40.Helper.Show(a(this).parents(".gaat40-subsubnav"))}).blur(function(){GAAT40.Helper.Hide(d.parents("li").find(c))})})()};GAAT40.emailFriend=function(){var a="492",b=GAAT40.renderSettings.culture;b=="pl_PL"&&(a="562");b=="cs_CZ"|b=="es_MX"|b=="es_LA"|b=="es_ES"|b=="nl_NL"|b=="pt_BR"&&(a="542");
b=="he_IL"&&(a="502");b=="fr_FR"|b=="vi_VN"&&(a="462");b=="uk_UA"&&(a="455");window.open(GAAT40.AssetPath+"/sites/sitewide/"+b+"/emailfriend.htm?param="+document.location.href,"emailfriend","width="+a+", height=550,menubar=no ,toolbar=no, resizable=yes, left=60, top=40")};GAAT40.JSButtons=function(){(function(){GAAT40.renderSettings.enableEmailWidget&&(a(".gaat40-share").prepend('<a href="#" title="'+GAAT40.renderSettings.emailTxt+'" class="gaat40-email">'+GAAT40.renderSettings.emailTxt+"</a>"),a(".gaat40-email").click(function(b){b.preventDefault();
GAAT40.emailFriend()}));pathName=document.location.pathname.toLowerCase();if(GAAT40.ShareBlacklist)for(var c=0;c<GAAT40.ShareBlacklist.path.length;c++)pathName.indexOf(GAAT40.ShareBlacklist.path[c].value.toLowerCase())!=-1&&a(".gaat40-share").empty();GAAT40.renderSettings.enablePrintWidget&&(a(".gaat40-share").prepend('<a href="#" title="'+GAAT40.renderSettings.printTxt+'" class="gaat40-print">'+GAAT40.renderSettings.printTxt+"</a>"),a(".gaat40-print").click(function(b){b.preventDefault();window.print()}))})()};
GAAT40.ChangeLocation=function(){(function(){var c=a("#gaat40-locale");if(c.html()===null)return!1;if(!GAAT40.languages||!GAAT40.languages.countries)return!1;var b=new GAAT40.Helper.Cookie("countrylang"),b=unescape(b.read("countrylang"));if(b!==null)if(GAAT40.languages.countries.length>0)for(var d=0;d<GAAT40.languages.countries.length;d++)GAAT40.languages.countries[d].name==b&&c.find("a").eq(0).html(GAAT40.languages.countries[d].localizedCountry);else return!1})()};GAAT40.Helper={IsIE6:function(){var c=
!1;a.browser.msie&&a.browser.version=="6.0"&&(c=!0);return c},Hide:function(c){a(c).addClass("gaat40-hide")},Show:function(c){a(c).removeClass("gaat40-hide")},Cookie:function(a,b,d){this.name=a;this.value=b;this.days=d;this.create=function(){var e;d?(e=new Date,e.setTime(e.getTime()+d*864E5),e="; expires="+e.toGMTString()):e="";document.cookie=a+"="+b+e+";domain=.intel.com; path=/"};this.read=function(){for(var b=a+"=",d=document.cookie.split(";"),g=0;g<d.length;g++){for(var h=d[g];h.charAt(0)===
" ";)h=h.substring(1,h.length);if(h.indexOf(b)===0)return h.substring(b.length,h.length)}return null};this.erase=function(){createCookie(a,"",-1)}}};GAAT40.Init=function(){if(GAAT40.hasRun==!0)return!1;new GAAT40.DropDown(".gaat40-subsubnav");if(typeof GAAT40.FileType==="undefined")GAAT40.FileType="";a.ajax({async:!a.browser.mozilla,url:GAAT40.AssetPath+GAAT40.renderSettings.sitewidePath+"/js/json"+GAAT40.FileType+".js",dataType:"script",success:function(){new GAAT40.JSButtons;new GAAT40.ChangeLocation;
new GAAT40.NavigationHighlight}});a(".gaat40-navhide").removeClass("gaat40-navhide");GAAT40.FilterMenu();GAAT40.BrowserCheck();GAAT40.PageHistoryTracker();GAAT40.hasRun=!0};GAAT40.BrowserCheck=function(){a.browser.msie&&parseFloat(a.browser.version)<7&&INTEL(GAAT40.AssetPath+"/sites/sitewide/hat/40recode/js/modbrowsercheck.js")};GAAT40.PageHistoryTracker=function(){var a="";if(document.getElementsByTagName("title")[0])a=document.getElementsByTagName("title")[0].innerHTML;a=escape(window.location)+
":"+escape(a);if(document.cookie.match("INTELHistoryTracker")){var b=new GAAT40.Helper.Cookie("INTELHistoryTracker"),b=b.read().split(",");b[b.length-1]!=a&&(b.push(a),b.length>10&&b.shift(),b=new GAAT40.Helper.Cookie("INTELHistoryTracker",b.join(",")),b.create())}else b=new GAAT40.Helper.Cookie("INTELHistoryTracker",a),b.create()};GAAT40.FilterMenu=function(){if(!GAAT40.SearchFilterLUT||GAAT40.SearchFilterLUT.qs.length==0)return!1;var c="<ul id='HAT-filter-menu'>";c+="<li id='HAT-filterhead'>"+GAAT40.SearchFilterLUT.head+
"</li>";a(GAAT40.SearchFilterLUT.qs).each(function(){c+="<li><a href='?"+this.filter+"'>"+this.term+"</a></li>"});c+="</ul>";a("#HAT-filtermenu-container").append(c);a(".gaat40-btnsearch, #HAT-filter-menu").mouseover(function(){a("#HAT-filtermenu-container").removeClass("gaat40-hide")}).mouseout(function(){a("#HAT-filtermenu-container").addClass("gaat40-hide")});a(".gaat40-btnsearch, #HAT-filter-menu, #HAT-filter-menu a").focus(function(){a("#HAT-filtermenu-container").removeClass("gaat40-hide")}).blur(function(){a("#HAT-filtermenu-container").addClass("gaat40-hide")});
a("#HAT-filter-menu a").each(function(){a(this).click(function(a){a.preventDefault();if(document.getElementById("FORMSearchHeader"))if(a=this.href.substring(this.href.indexOf("?")+1),a!="HAT-adv1"?document.getElementById("category").value=a:document.getElementById("adv").value="1",document.getElementById("culture").value==="ja_JP"){if(document.getElementById("FORMSearchHeader")){var a=document.getElementById("FORMSearchHeader").action,d=document.getElementById("category").value,c=document.getElementById("adv").value,
f=document.getElementById("value").value;window.location=a+"?culture=ja_JP&q="+encodeURIComponent(document.getElementById("q").value)+"&category="+d+"&adv="+c+"&value="+f}}else document.getElementById("FORMSearchHeader").submit();return!1})});if(!document.getElementById("FORMSearchHeader"))return!1;if(document.getElementById("category"))document.getElementById("category").value="all";if(document.getElementById("adv"))document.getElementById("adv").value="0";if(document.getElementById("value"))document.getElementById("value").value=
"0";(new function(){var a,d,c=0;this.Add=function(f){if(GAAT40.Helper.IsIE6()&&f.find("iframe").length===0){d=f;a=f.html();var g=d.width(),h=d.height();f.wrapInner('<div style="z-index:1;position:relative;zoom:1"></div>');f.append('<iframe id="HAT-filter-menu-iframe" src="javascript:\'\'" frameborder="0" style="z-index:0;position:absolute;top:0;right:0; width: '+g+"px; height: "+h+'px;"></iframe>')}c++};this.Remove=function(){c>0&&GAAT40.Helper.IsIE6()&&(d.html(a),c=0)}}).Add(a("#HAT-filtermenu-container"))};
GAAT40.Init()};typeof jQuery==="undefined"&&typeof INTEL!=="undefined"&&typeof INTEL.jquery==="undefined"?INTEL("jquery",function(){GAAT40.main(jQuery)}):typeof jQuery==="undefined"&&typeof INTEL!=="undefined"&&typeof INTEL.jquery!=="undefined"?(jQuery=INTEL.jquery,GAAT40.main(jQuery)):typeof jQuery!=="undefined"&&GAAT40.main(jQuery);function sectionOn(){}function hideAllMenus(){}function writeMenus(){}var _gaq=_gaq||[];_gaq.push(["GAtracker._setAccount","UA-23487238-1"]);_gaq.push(["GAtracker._setDomainName","none"]);_gaq.push(["GAtracker._setAllowLinker",!0]);_gaq.push(["GAtracker._setCustomVar",1,"HeaderVersion","40recodeA",3]);_gaq.push(["GAtracker._setCustomVar",2,"HeaderChosen",".Base.40recodeA",3]);
_gaq.push(["GAtracker._setCustomVar",3,"HeaderSubNav",GAAT40.renderSettings.OutputId+".Base.40recodeA",3]);_gaq.push(["GAtracker._setCustomVar",4,"HeaderGEO",GAAT40.renderSettings.culture+"."+GAAT40.renderSettings.OutputId+".Base.40recodeA",3]);_gaq.push(["GAtracker._trackPageview"]);(function(){var a=document.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"==document.location.protocol?"https://ssl":"http://www")+".google-analytics.com/ga.js";var c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(a,c)})();